[[pages]]
path = "pages/intro.py"
name = "Jobb's ML Projects"
icon = "â„ï¸"

[[pages]]
path = "pages/comment_analyzer.py"
name = "Comment Analyzer"
icon = "ğŸ”"

[[pages]]
path = "pages/customer_segmentation.py"
name = "Customer Segmentation"
icon = "ğŸ”®"

[[pages]]
path = "pages/dogs_vs_cats.py"
name = "Dogs vs. Cats"
icon = "ğŸ¶"
